server:
  port: 8085

  #  controller全局前置路径
  servlet:
    context-path: /api
spring:
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: "GMT+8"
  jpa:
    hibernate:
      ddl-auto: none
    #    open-in-view: true
    #    配置懒加载
    properties:
      hibernate:
        format_sql: true
    #        enable_lazy_load_no_trans: false
    #    控制台打印jpa执行的sql
    show-sql: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.42.104.145:3306/mine
#    url: jdbc:mysql://127.0.0.1:3306/mine


    username: root
    password: miaoshidahu

    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 连接池初始化大小
      initial-size: 10
      # 最大活动连接数
      max-active: 200
      # 最小空闲连接数
      min-idle: 10










springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui


#
logging:
  level:
    com.example: debug

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,info,heapdump  # 暴露 health、metrics、info 和 heapdump 端点
#  endpoint:
#    metrics:
#      enabled: true  # 启用 metrics 端点
#    heapdump:
#      enabled: true  # 启用 heapdump 端点